export type ServiceFaq = {
  question: string
  answer: string
}

export type ServiceIntent = {
  slug: string
  title: string
  description: string
  eyebrow: string
  heading: string
  lede: string
  problem: string
  whoFor: string
  benefits: string[]
  examples: string[]
  faq: ServiceFaq[]
}

export const SERVICE_INTENTS: ServiceIntent[] = [
  {
    slug: 'ai-claim-verification',
    title: 'AI Claim Verification Service | ProofTTL',
    description: 'Verify factual claims produced by AI against public primary sources before you publish, send, sell, or rely on them.',
    eyebrow: 'AI CLAIM VERIFICATION',
    heading: 'Verify the factual claims AI gives you before they become your problem.',
    lede: 'ProofTTL pressure-tests specific AI-generated factual claims against public primary sources and returns explicit SUPPORTED, CONTRADICTED, or UNKNOWN verdicts with evidence.',
    problem: 'AI can produce fluent statements that sound settled even when the underlying facts are incomplete, stale, or wrong. Generic hallucination scores do not tell you which source supports the exact sentence you are about to use.',
    whoFor: 'Teams using ChatGPT, Claude, Gemini, Copilot, Perplexity, custom agents, RAG systems, or AI-assisted research for customer-facing or decision-critical work.',
    benefits: ['Claim-by-claim source checking', 'Primary-source evidence links', 'Explicit uncertainty instead of forced certainty', 'Signed Fact Leases for the source observation', '48-hour $129 stress-test option for 3–5 high-stakes claims'],
    examples: ['“This vendor is SOC 2 Type II certified.”', '“This market grew 38% last year.”', '“This product supports SAML SSO on the current plan.”'],
    faq: [
      { question: 'Can ProofTTL check facts generated by ChatGPT or another AI?', answer: 'Yes. ProofTTL can take specific factual claims from AI-generated output and check them against public sources. It does not need the claim to come from a particular model.' },
      { question: 'Is ProofTTL an AI hallucination detector?', answer: 'Not in the generic scoring sense. ProofTTL verifies specific factual claims against sources and reports what the examined evidence supports, contradicts, or leaves unknown.' },
      { question: 'What does AI claim verification cost?', answer: 'The Claim Stress Test is $129 for 3–5 high-stakes claims. A Full Verification Audit is $500 for 10–25 claims. Scope is confirmed before payment.' },
    ],
  },
  {
    slug: 'ai-output-fact-checking',
    title: 'AI Output Fact-Checking Service | ProofTTL',
    description: 'Fact-check AI-written reports, research, sales copy, briefs, and answers against public sources with evidence attached to each verdict.',
    eyebrow: 'AI OUTPUT FACT-CHECKING',
    heading: 'Turn AI-written output into claims you can actually defend.',
    lede: 'ProofTTL reviews the factual assertions inside AI-assisted work, prioritizes the claims that can create real downside, and verifies them against inspectable public evidence.',
    problem: 'A long AI answer may contain dozens of assertions, but only a few can damage trust, trigger corrections, or derail a deal. Those are the claims worth pressure-testing before the work leaves your hands.',
    whoFor: 'Operators, consultants, agencies, researchers, founders, analysts, and teams shipping AI-assisted documents or customer-facing material.',
    benefits: ['High-risk claims prioritized first', 'Evidence attached to each checked assertion', 'Contradictions surfaced before publication', 'UNKNOWN preserved when evidence is insufficient', 'Full audit option for 10–25 claims'],
    examples: ['AI-generated market research', 'AI-assisted client reports', 'AI-written sales or product copy'],
    faq: [
      { question: 'Can I send ProofTTL an entire AI-written report?', answer: 'Yes, but the paid service is scoped around the factual claims that matter most. The $129 Stress Test covers 3–5 claims and the $500 Full Verification Audit covers 10–25 claims.' },
      { question: 'Does ProofTTL rewrite the document?', answer: 'The core service verifies claims and provides evidence and verdicts. Scope can include a concise summary, but the verification result is kept separate from unsupported rewriting.' },
      { question: 'Does ProofTTL hide uncertain results?', answer: 'No. UNKNOWN remains UNKNOWN when the examined evidence does not justify a stronger verdict.' },
    ],
  },
  {
    slug: 'ai-hallucination-checking',
    title: 'AI Hallucination Claim Checking | ProofTTL',
    description: 'Check suspicious or high-stakes AI claims against public primary sources instead of relying on a generic hallucination score.',
    eyebrow: 'AI HALLUCINATION CHECKING',
    heading: 'Do not ask whether the whole answer “looks hallucinated.” Check the claim that matters.',
    lede: 'ProofTTL is built for concrete factual verification: isolate the risky assertion, inspect the best available public evidence, and record an explicit verdict with the source context.',
    problem: 'Hallucination detectors can estimate risk, but a buyer, editor, investor, or customer may still ask one simple question: what source proves this specific claim?',
    whoFor: 'Anyone who has an AI-generated statement they need to rely on, publish, present, or defend.',
    benefits: ['Specific claim verification rather than generic scoring', 'Source URLs and evidence context', 'SUPPORTED / CONTRADICTED / UNKNOWN outcomes', 'Signed source-observation record', 'No payment until scope is confirmed'],
    examples: ['“The FDA approved this use in 2025.”', '“Competitor X charges $49 per user.”', '“The company announced 2 million active users.”'],
    faq: [
      { question: 'Can ProofTTL prove that an AI hallucinated?', answer: 'ProofTTL can show that a specific AI-generated factual claim is contradicted by, unsupported by, or supported by the examined sources. It does not claim to read the model’s internal reasoning.' },
      { question: 'What if there is no reliable public source?', answer: 'The claim can remain UNKNOWN. ProofTTL does not manufacture certainty when the public evidence is insufficient.' },
      { question: 'Can I start with only one suspicious section?', answer: 'The standard entry offer is a $129 Claim Stress Test covering 3–5 high-stakes claims.' },
    ],
  },
  {
    slug: 'pre-publication-fact-checking',
    title: 'Pre-Publication Fact-Checking Service | ProofTTL',
    description: 'Check high-stakes factual claims before an article, report, pitch, website, launch, or public statement goes live.',
    eyebrow: 'PRE-PUBLICATION FACT-CHECKING',
    heading: 'Find the correction before your audience does.',
    lede: 'ProofTTL pressure-tests factual claims before publication so unsupported numbers, outdated policy statements, and overconfident assertions can be caught while they are still cheap to fix.',
    problem: 'Once a claim is public, the cost is no longer just editing. It can become a correction, credibility hit, client problem, lost deal, or screenshot that never disappears.',
    whoFor: 'Publishers, agencies, founders, consultants, researchers, analysts, and anyone releasing factual material under their name or brand.',
    benefits: ['Review before public exposure', 'Primary-source links for each verdict', 'Contradictions prioritized', 'Fast 48-hour stress test', 'Full audit with 7-day monitoring'],
    examples: ['Launch announcements', 'Research reports', 'Investor decks and public claims'],
    faq: [
      { question: 'How fast is the pre-publication review?', answer: 'The Claim Stress Test targets 48 hours after payment and scope confirmation. The Full Verification Audit targets 3–5 business days.' },
      { question: 'Can ProofTTL guarantee a publication has no errors?', answer: 'No. ProofTTL checks the scoped factual claims against examined sources. It does not guarantee a document contains no possible error.' },
      { question: 'Do I pay before ProofTTL reviews the scope?', answer: 'No. The intake is reviewed first and the exact scope is confirmed before a payment request is created.' },
    ],
  },
  {
    slug: 'marketing-claim-verification',
    title: 'Marketing Claim Verification Service | ProofTTL',
    description: 'Verify factual marketing, product, comparison, performance, and company claims against public evidence before campaigns go live.',
    eyebrow: 'MARKETING CLAIM VERIFICATION',
    heading: 'Make the claim persuasive without making it indefensible.',
    lede: 'ProofTTL checks the factual layer underneath marketing copy: numbers, comparisons, feature availability, company statements, market statistics, and externally verifiable assertions.',
    problem: 'Marketing language moves fast. A number from an old deck or a feature claim copied from a stale page can turn into a credibility problem the moment a customer checks it.',
    whoFor: 'Marketing teams, agencies, founders, product marketers, sales teams, and consultants publishing factual claims about products, markets, companies, or competitors.',
    benefits: ['Product and feature claim verification', 'Comparison claims checked against sources', 'Market-statistic verification', 'Evidence you can hand to reviewers', 'Small-scope stress test before major campaigns'],
    examples: ['“Used by more than 10,000 teams.”', '“The only platform with feature X.”', '“Customers save 30% on average.”'],
    faq: [
      { question: 'Does ProofTTL review legal advertising compliance?', answer: 'No. ProofTTL verifies scoped factual claims against sources. It does not replace legal or regulatory review.' },
      { question: 'Can ProofTTL check competitor comparison claims?', answer: 'Yes, when the comparison can be evaluated against accessible public evidence.' },
      { question: 'Can we verify claims before an ad or landing page launches?', answer: 'Yes. Pre-launch verification is one of the main uses of the Claim Stress Test.' },
    ],
  },
  {
    slug: 'startup-claim-verification',
    title: 'Startup Claim Verification for Pitches, Launches & Fundraising | ProofTTL',
    description: 'Pressure-test startup market, traction, competitor, product, and industry claims before a pitch, launch, investor meeting, or diligence process.',
    eyebrow: 'STARTUP CLAIM VERIFICATION',
    heading: 'Pressure-test the sentence an investor, customer, or journalist is most likely to challenge.',
    lede: 'ProofTTL checks externally verifiable startup claims before they reach a pitch deck, fundraising conversation, launch page, or public announcement.',
    problem: 'A deck can be directionally right and still contain one brittle statistic or comparison that causes the entire presentation to feel less credible when challenged.',
    whoFor: 'Founders and small teams preparing pitches, fundraising materials, launch claims, competitive positioning, or investor updates.',
    benefits: ['Market-size and growth claims checked', 'Competitor and feature assertions reviewed', 'Public traction claims pressure-tested', 'Evidence packaged for follow-up questions', '$129 entry point before a major meeting'],
    examples: ['“This is a $12B market growing 22% annually.”', '“No competitor offers this workflow.”', '“The category has doubled since 2023.”'],
    faq: [
      { question: 'Can ProofTTL verify my private revenue or customer metrics?', answer: 'The standard service is built around public-source verification. Private internal metrics require different evidence and must be scoped separately.' },
      { question: 'Can ProofTTL check a pitch deck?', answer: 'Yes. The service can scope the factual claims in a pitch deck that are most likely to be challenged.' },
      { question: 'Is ProofTTL investment advice?', answer: 'No. It is a claim-verification service and does not provide investment, legal, or financial advice.' },
    ],
  },
  {
    slug: 'due-diligence-claim-verification',
    title: 'Due Diligence Claim Verification Service | ProofTTL',
    description: 'Independently check selected public factual claims in vendor, partner, acquisition, investment, or procurement diligence.',
    eyebrow: 'DUE DILIGENCE CLAIM VERIFICATION',
    heading: 'Verify the public claim before you let it into the decision.',
    lede: 'ProofTTL can independently check selected public claims made by a vendor, partner, company, or project and return the sources and verdicts behind the review.',
    problem: 'Diligence often includes claims copied between websites, decks, press releases, and third-party summaries. Repetition is not the same thing as independent support.',
    whoFor: 'Operators, procurement teams, consultants, founders, analysts, and buyers who need a source-backed check on a defined set of public claims.',
    benefits: ['Independent public-source checking', 'Evidence separated from marketing language', 'Contradictions and gaps surfaced explicitly', 'Scoped review instead of open-ended research', 'Signed Fact Lease records for checked claims'],
    examples: ['Security or compliance claims', 'Partnership and customer claims', 'Product availability or geographic coverage claims'],
    faq: [
      { question: 'Is ProofTTL a full due-diligence firm?', answer: 'No. ProofTTL verifies scoped factual claims against available sources. It does not replace legal, financial, technical, or investigative due diligence.' },
      { question: 'Can ProofTTL verify certifications or partnerships?', answer: 'Yes, when the claim can be evaluated using authoritative public evidence.' },
      { question: 'Can I choose only the claims I care about?', answer: 'Yes. The paid flow is explicitly scope-first so the exact claims are agreed before payment.' },
    ],
  },
  {
    slug: 'research-claim-verification',
    title: 'Research Claim Verification & Source Checking | ProofTTL',
    description: 'Check factual assertions, statistics, dates, product facts, and source-backed statements in research before they are cited or delivered.',
    eyebrow: 'RESEARCH CLAIM VERIFICATION',
    heading: 'Keep the citation attached to the claim it actually supports.',
    lede: 'ProofTTL verifies selected research claims against inspectable sources and records the evidence used for each verdict instead of treating a bibliography as proof of every sentence.',
    problem: 'Research can look well-sourced while individual statements quietly outrun what the cited source actually says. Claim-level verification catches that gap.',
    whoFor: 'Researchers, analysts, consultants, writers, agencies, founders, and AI-assisted research workflows.',
    benefits: ['Claim-to-source alignment checking', 'Statistics and dates verified at the assertion level', 'Contradictory evidence surfaced', 'UNKNOWN used when the evidence is insufficient', 'Audit-friendly source links and verdicts'],
    examples: ['Market statistics', 'Historical dates and policy statements', 'Product, company, or industry facts'],
    faq: [
      { question: 'Does ProofTTL replace academic peer review?', answer: 'No. It checks scoped factual claims against sources and does not replace peer review or domain-expert methodology review.' },
      { question: 'Can ProofTTL check whether a citation really supports the sentence?', answer: 'Yes. Claim-to-source alignment is a core verification use case.' },
      { question: 'Can AI-assisted research be checked?', answer: 'Yes. ProofTTL evaluates the factual claims themselves regardless of whether a human or AI produced the draft.' },
    ],
  },
  {
    slug: 'website-claim-audit',
    title: 'Website Claim Audit & Fact-Checking Service | ProofTTL',
    description: 'Audit factual claims on a website, landing page, product page, pricing page, or company profile against current public sources.',
    eyebrow: 'WEBSITE CLAIM AUDIT',
    heading: 'Audit the facts your website keeps repeating after everyone forgets where they came from.',
    lede: 'ProofTTL checks selected factual claims already live or about to go live on your website and identifies statements that are unsupported, contradicted, or stale.',
    problem: 'Websites accumulate facts over time: customer counts, product availability, pricing claims, certifications, market numbers, comparison language, and old launch copy. Those claims can stay online long after their evidence changes.',
    whoFor: 'Founders, agencies, product teams, marketing teams, consultants, and businesses updating or relaunching public websites.',
    benefits: ['High-risk website claims prioritized', 'Current source checks', 'Stale or contradicted claims surfaced', 'Evidence links for internal review', '7-day monitoring included with the full audit'],
    examples: ['Homepage statistics', 'Pricing and plan claims', 'Product, integration, certification, or coverage statements'],
    faq: [
      { question: 'Can ProofTTL crawl my entire site?', answer: 'The paid service is scoped by claims rather than sold as an unlimited crawler. The $129 Stress Test covers 3–5 claims and the Full Verification Audit covers 10–25.' },
      { question: 'Can ProofTTL check stale claims?', answer: 'Yes. The verification process can identify when current public evidence no longer supports a claim that remains on the site.' },
      { question: 'Does the full audit include monitoring?', answer: 'Yes. The $500 Full Verification Audit includes 7 days of monitoring for the scoped claims.' },
    ],
  },
  {
    slug: 'source-backed-fact-checking',
    title: 'Source-Backed Fact-Checking Service | ProofTTL',
    description: 'Get claim-level fact checking with explicit verdicts, public source links, evidence context, and signed Fact Leases.',
    eyebrow: 'SOURCE-BACKED FACT-CHECKING',
    heading: 'A fact-check is more useful when another person can inspect why it exists.',
    lede: 'ProofTTL ties every checked claim to the source observation and evidence used to produce the verdict, so the result can be inspected instead of accepted as a black box.',
    problem: 'A bare true/false label is hard to audit and even harder to defend later. Source-backed verification keeps the claim, evidence, verdict, and timing connected.',
    whoFor: 'Anyone who needs more than a confidence score or an unsupported answer from another model.',
    benefits: ['Public source links', 'Evidence context with each verdict', 'SUPPORTED / CONTRADICTED / UNKNOWN outcomes', 'Signed Fact Lease records', 'Scope confirmed before any payment request'],
    examples: ['Business claims', 'AI-generated claims', 'Research and publication claims'],
    faq: [
      { question: 'What makes ProofTTL source-backed?', answer: 'The result stays tied to the source URL and the evidence used for the verdict rather than returning a detached answer.' },
      { question: 'Does ProofTTL only return true or false?', answer: 'No. The paid service uses SUPPORTED, CONTRADICTED, or UNKNOWN so insufficient evidence is not forced into a binary result.' },
      { question: 'How do I start?', answer: 'Submit the claims through the audit intake. ProofTTL reviews the scope first, then sends a payment request only after the scope is confirmed.' },
    ],
  },
]

export function getServiceIntent(slug: string) {
  return SERVICE_INTENTS.find((intent) => intent.slug === slug)
}
