import type { Metadata } from 'next'
import AuditIntakeForm from '../../components/AuditIntakeForm'

const SITE_URL = 'https://proofttl-web.vercel.app'

const AUDIT_FAQ = [
  { question: 'Can ProofTTL verify claims generated by AI?', answer: 'Yes. ProofTTL can check specific factual claims from ChatGPT, Claude, Gemini, Copilot, Perplexity, custom agents, RAG systems, or human-written content against public sources.' },
  { question: 'Do I pay before ProofTTL reviews my claims?', answer: 'No. The intake is reviewed first. ProofTTL confirms the exact scope, price, and turnaround before creating the payment request.' },
  { question: 'What happens if the evidence is not strong enough?', answer: 'The verdict stays UNKNOWN. ProofTTL does not force uncertain evidence into a supported or contradicted result.' },
  { question: 'What does the $129 Claim Stress Test include?', answer: 'It covers 3–5 high-stakes factual claims with source-backed verdicts and signed Fact Leases, targeting a 48-hour turnaround after payment and scope confirmation.' },
]

export const metadata: Metadata = {
  title: 'Claim Verification Service — $129 Stress Test & $500 Audit',
  description: 'ProofTTL fact-checks AI-generated and human-written factual claims against public primary sources. Verify 3–5 claims for $129 or 10–25 claims for $500. Scope before payment.',
  keywords: ['claim verification service', 'fact checking service', 'AI claim verification', 'AI fact checking', 'source-backed fact checking', 'claim stress test', 'verification audit', 'factual claim audit'],
  alternates: { canonical: '/audit/' },
  openGraph: {
    title: 'ProofTTL Claim Verification & Fact-Checking Service',
    description: 'Source-backed claim verification starting at $129. AI-generated or human-written claims. Scope is confirmed before payment.',
    url: '/audit/',
    type: 'website',
  },
}

export default function AuditPage() {
  const structuredData = {
    '@context': 'https://schema.org',
    '@graph': [
      {
        '@type': 'Service',
        '@id': `${SITE_URL}/audit/#service`,
        name: 'ProofTTL Claim Verification & Fact-Checking Service',
        serviceType: 'Source-backed factual claim verification',
        url: `${SITE_URL}/audit/`,
        provider: { '@id': `${SITE_URL}/#organization` },
        areaServed: 'Worldwide',
        description: 'Verification of scoped factual claims against public sources with SUPPORTED, CONTRADICTED, or UNKNOWN verdicts, evidence, and signed Fact Leases.',
      },
      {
        '@type': 'FAQPage',
        '@id': `${SITE_URL}/audit/#faq`,
        mainEntity: AUDIT_FAQ.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })),
      },
    ],
  }

  return (
    <main className="app-page audit-sales-page">
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }} />
      <section className="onboarding-wrap">
        <div className="audit-sales-card">
          <header className="audit-sales-hero">
            <p className="app-kicker">SOURCE-BACKED CLAIM VERIFICATION</p>
            <h1 className="app-title">Find the claim that breaks before someone else does.</h1>
            <p className="app-copy">Send the factual claims you are about to publish, sell, raise on, launch, or defend — including claims produced by AI. ProofTTL checks them against public primary sources and returns explicit verdicts with evidence.</p>
            <div className="audit-sales-trustline">
              <span>NO CARD TO SUBMIT</span>
              <span>SCOPE BEFORE PAYMENT</span>
              <span>REVIEW WITHIN 24H</span>
            </div>
          </header>

          <div className="audit-offer-summary" aria-label="Verification offer summary">
            <div>
              <span>START SMALL</span>
              <strong>$129 Claim Stress Test</strong>
              <small>3–5 claims · 48-hour turnaround</small>
            </div>
            <div>
              <span>FULL REVIEW</span>
              <strong>$500 Full Verification Audit</strong>
              <small>10–25 claims · 3–5 business-day turnaround</small>
            </div>
            <p>Start at $129 and upgrade later for <strong>$371 more</strong>. Your first payment is credited in full.</p>
          </div>

          <AuditIntakeForm />

          <section className="audit-sales-proof">
            <div>
              <p className="app-kicker">WHAT YOU GET</p>
              <ul className="audit-clean-list">
                <li>SUPPORTED, CONTRADICTED, or UNKNOWN for every checked claim</li>
                <li>Primary-source links and the evidence used for each verdict</li>
                <li>Signed ProofTTL Fact Leases tied to the source observation</li>
                <li>A concise summary you can hand to a client, teammate, investor, or reviewer</li>
              </ul>
            </div>
            <div className="audit-sample-card">
              <p className="app-kicker">WANT PROOF FIRST?</p>
              <p className="app-copy">Inspect the public sample and see the claim set, sources, verdict logic, contradictions, and uncertainty handling.</p>
              <a className="button button-secondary" href="/audit/sample/">VIEW SAMPLE AUDIT →</a>
            </div>
          </section>

          <section className="audit-sales-steps">
            <p className="app-kicker">WHAT HAPPENS NEXT</p>
            <div className="audit-step-grid">
              <div><strong>1</strong><span>Submit claims</span><small>No payment.</small></div>
              <div><strong>2</strong><span>Scope review</span><small>Within 24 hours.</small></div>
              <div><strong>3</strong><span>Approve + pay</span><small>Secure Stripe checkout.</small></div>
              <div><strong>4</strong><span>Receive results</span><small>Evidence + verdicts.</small></div>
            </div>
          </section>

          <section style={{ margin: '28px 34px 0' }} aria-labelledby="audit-faq-heading">
            <div style={{ display: 'flex', justifyContent: 'space-between', gap: 18, alignItems: 'end', flexWrap: 'wrap', paddingBottom: 14 }}>
              <div>
                <p className="app-kicker" style={{ marginBottom: 8 }}>COMMON QUESTIONS</p>
                <h2 id="audit-faq-heading" style={{ margin: 0, fontSize: 'clamp(24px,3vw,32px)', letterSpacing: '-.03em' }}>Before you send the claims.</h2>
              </div>
              <a className="text-link" href="/faq/">FULL FAQ →</a>
            </div>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(280px,1fr))', gap: 10 }}>
              {AUDIT_FAQ.map((item, index) => (
                <article key={item.question} style={{ minHeight: 154, padding: 18, border: '1px solid rgba(148,163,184,.11)', borderRadius: 12, background: index === 0 ? 'linear-gradient(180deg,rgba(34,211,238,.045),rgba(255,255,255,.012))' : 'rgba(255,255,255,.014)' }}>
                  <span style={{ display: 'block', marginBottom: 12, color: '#5f7187', font: "700 8px 'IBM Plex Mono',monospace", letterSpacing: '.1em' }}>0{index + 1}</span>
                  <h3 style={{ margin: '0 0 8px', fontSize: 16, lineHeight: 1.25 }}>{item.question}</h3>
                  <p className="app-copy" style={{ margin: 0, fontSize: 12, lineHeight: 1.6 }}>{item.answer}</p>
                </article>
              ))}
            </div>
          </section>

          <div className="hero-actions" style={{ margin: '20px 34px 0' }}>
            <a className="text-link" href="/services/">SEE VERIFICATION USE CASES →</a>
            <a className="text-link" href="/trust/">READ TRUST BOUNDARIES →</a>
          </div>

          <p className="app-note audit-limit-note">UNKNOWN stays UNKNOWN. ProofTTL records what examined sources supported at a point in time; it does not create legal authority, guarantee future truth, or replace professional legal, financial, medical, or regulatory judgment.</p>
        </div>
      </section>
    </main>
  )
}
