export default function CommercialHome() {
  return <main className="ptl-home ptl-ai-home" id="top"><section className="ptl-ai-shell shell">
    <aside className="ptl-ai-sidebar" aria-label="ProofTTL quick access"><a className="ptl-ai-mark" href="#top" aria-label="ProofTTL home"><img src="/proofttl-mark.svg" alt="" /></a><nav><a className="active" href="#top"><b>⌁</b><span>Verify</span></a><a href="/audit/sample/"><b>◈</b><span>Sample</span></a><a href="/how-proofttl-works/"><b>◎</b><span>Method</span></a><a href="/trust/"><b>◇</b><span>Trust</span></a></nav><a className="ptl-ai-help" href="/support/"><b>?</b><span>Support</span></a></aside>
    <div className="ptl-ai-main"><header className="ptl-ai-topbar"><div><span className="ptl-live-dot"/><strong>ProofTTL</strong><small>Verification</small></div><div className="ptl-ai-top-actions"><a href="/audit/sample/">Sample</a><a className="ptl-ai-top-cta" href="/audit/#audit-intake">Start the $1,500 Fact Audit <span>↗</span></a></div></header>
      <section className="ptl-ai-hero"><div className="ptl-ai-hero-copy"><div className="ptl-ai-eyebrow"><span>✦</span> Fact Audit</div><h1>What do you need<br/><em>verified?</em></h1><p>Find the expensive wrong answer before your customer does. Give ProofTTL the AI outputs your users actually see. We isolate the claims, inspect authoritative evidence, test contradictions, and return a human-approved finding.</p></div><div className="ptl-ai-composer" role="group" aria-label="Start a ProofTTL verification"><div className="ptl-ai-composer-input"><span>Paste an output, claim, or source to verify</span></div><div className="ptl-ai-composer-tools"><div><button type="button" aria-label="Attach evidence">＋</button><span>Up to 25 outputs</span></div><a href="/audit/" aria-label="Open Fact Audit">↑</a></div></div><div className="ptl-ai-shortcuts"><a href="/audit/"><span>⌁</span><div><strong>Audit outputs</strong></div></a><a href="/audit/sample/"><span>◈</span><div><strong>View a finding</strong></div></a><a href="/how-proofttl-works/"><span>◎</span><div><strong>How it works</strong></div></a></div><div className="ptl-hero-trust"><span>UP TO 25 OUTPUTS</span><span>SCOPE CONFIRMED BEFORE PAYMENT</span><span>HUMAN APPROVAL</span><span>7-DAY WATCH</span></div></section>
      <section className="ptl-ai-workspace" aria-label="Verification workspace preview"><div className="ptl-ai-workspace-head"><div><span>Finding preview</span><strong>One claim. Both sides of the evidence.</strong></div><div className="ptl-ai-status"><i/> Ready</div></div><div className="ptl-ai-workspace-grid"><div className="ptl-ai-claim-panel"><div className="ptl-ai-panel-label"><span>01</span> Claim</div><blockquote>“The reviewed assertion remains supported by current authoritative guidance.”</blockquote><div className="ptl-ai-risk"><span>Consequence</span><strong>High</strong><small>Customer-facing factual output</small></div></div><div className="ptl-ai-evidence-panel"><div className="ptl-ai-panel-label"><span>02</span> Evidence</div><article><i className="for"/><div><small>FOR</small><strong>Primary source supports part of the assertion</strong><span>Authoritative · current</span></div></article><article><i className="against"/><div><small>AGAINST</small><strong>Newer guidance conflicts with the claim as written</strong><span>Primary source · newer</span></div></article></div><div className="ptl-ai-verdict-panel"><div className="ptl-ai-panel-label"><span>03</span> Verdict</div><div className="ptl-ai-verdict-orb">×</div><strong>CONTRADICTED</strong><p>The strongest current source conflicts with the scoped claim.</p><div className="ptl-ai-human">✓ Human approval required</div></div></div></section>
      <section className="ptl-ai-section"><div className="ptl-ai-section-title"><span>Built for scrutiny</span><h2>The proof stays simple.<br/>The work underneath doesn’t.</h2><p>Every important finding keeps the evidence, contradiction pass, uncertainty, and human decision close enough to inspect.</p></div><div className="ptl-ai-bento"><article className="wide"><div className="ptl-ai-card-glow"/><span>Evidence</span><h3>Sources organized around the exact claim.</h3><p>Support and contradiction are kept separate. Authority and freshness stay visible. You can see why a verdict exists without digging through a wall of machine output.</p><div className="ptl-ai-mini-sources"><i/><i/><i/><b>+12</b></div></article><article><span>Uncertainty</span><h3>UNKNOWN is allowed.</h3><p>If evidence is incomplete, ProofTTL does not manufacture confidence.</p><strong className="ptl-ai-unknown">UNKNOWN</strong></article><article><span>Human review</span><h3>Important findings have a gate.</h3><p>Automation assembles the case. A human controls the customer-facing result.</p><div className="ptl-ai-approval"><i>✓</i><span>Ready for review</span></div></article></div></section>
      <section className="ptl-ai-offer"><div><span>Fact Audit</span><h2>$1,500</h2><p>Up to 25 real outputs. Highest-risk findings deep-verified. Human approval and a seven-day watch included.</p></div><div className="ptl-ai-offer-actions"><a href="/audit/">Open Fact Audit <span>↗</span></a><a href="/audit/sample/">View sample</a><small>No subscription. No raw card number is stored by ProofTTL; payment is handled through Stripe after scope confirmation.</small></div></section>
      <footer className="ptl-ai-footer"><img src="/proofttl-lockup.svg" alt="ProofTTL"/><span>Evidence before confidence.</span><nav><a href="/about/">About</a><a href="/trust/">Trust</a><a href="/privacy/">Privacy</a><a href="/terms/">Terms</a></nav></footer>
    </div></section></main>
}
