'use client'

import { useMemo, useState } from 'react'

function cinematicDocument(prompt: string, seed: number) {
  const safePrompt = JSON.stringify(String(prompt || '').slice(0, 900)).replace(/</g, '\\u003c')
  return `<!doctype html><html><head><meta charset="utf-8"><style>
html,body{margin:0;width:100%;height:100%;overflow:hidden;background:#09090b;font-family:ui-monospace,Menlo,monospace;color:#fff}canvas{display:block;width:100%;height:100%;cursor:crosshair}.hud{position:fixed;inset:0;pointer-events:none}.top{position:absolute;top:12px;left:12px;right:12px;display:flex;justify-content:space-between;gap:8px;font-size:10px;letter-spacing:.1em}.badge{padding:7px 9px;border:1px solid #ffffff26;background:#08080bcc;backdrop-filter:blur(8px)}.controls{pointer-events:auto;position:absolute;top:50px;left:12px;display:flex;gap:6px;flex-wrap:wrap;max-width:70%}.controls button{border:1px solid #ffffff2f;background:#0d1016d9;color:#fff;padding:7px 9px;font:700 9px ui-monospace,Menlo,monospace;letter-spacing:.06em;cursor:pointer}.controls button.active{border-color:#f2c94c;color:#f2c94c}.bottom{position:absolute;left:12px;right:12px;bottom:12px;display:flex;justify-content:space-between;align-items:end;gap:12px}.prompt{max-width:68%;padding:8px 10px;background:#08080bcc;border-left:2px solid #f2c94c;font:10px/1.4 ui-monospace,Menlo,monospace;color:#ddd}.record{pointer-events:auto;border:1px solid #ffffff35;background:#111318e8;color:#fff;padding:9px 11px;font:700 9px ui-monospace,Menlo,monospace;letter-spacing:.08em;cursor:pointer}.record:hover,.controls button:hover{background:#23262d}.record:disabled{opacity:.55;cursor:default}.flash{position:absolute;inset:0;background:white;opacity:0;mix-blend-mode:screen}.hint{position:absolute;right:12px;top:92px;padding:7px 9px;background:#08080baa;border:1px solid #ffffff1c;color:#aaa;font-size:9px}
</style></head><body><div id="app"></div><div class="hud"><div class="top"><span class="badge">PROOFTTL · LOCAL CINEMATIC</span><span class="badge">GRAPHIC MARTIAL-ARTS PREVIEW</span></div><div class="controls"><button data-mode="technical" class="active">TECHNICAL</button><button data-mode="aggressive">AGGRESSIVE</button><button data-mode="defensive">DEFENSIVE</button><button id="cameraBtn">CAMERA: DIRECTOR</button><button id="pauseBtn">PAUSE</button></div><div class="hint">CLICK THE FLOOR TO MOVE THE FIGHT</div><div class="flash" id="flash"></div><div class="bottom"><div class="prompt" id="prompt"></div><button class="record" id="record">RECORD 12S WEBM</button></div></div><script type="module">
import * as THREE from 'https://esm.sh/three@0.179.1';
const prompt=${safePrompt}; const seed=${seed}; document.querySelector('#prompt').textContent=prompt;
let s=seed||1; const rand=()=>((s=Math.imul(1664525,s)+1013904223|0)>>>0)/4294967296;
const scene=new THREE.Scene(); scene.background=new THREE.Color(0x0b0b0d); scene.fog=new THREE.Fog(0x0b0b0d,10,34);
const camera=new THREE.PerspectiveCamera(46,innerWidth/innerHeight,.1,100); camera.position.set(8,4.6,11);
const renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true}); renderer.setPixelRatio(Math.min(devicePixelRatio,1.75)); renderer.setSize(innerWidth,innerHeight); renderer.shadowMap.enabled=true; renderer.shadowMap.type=THREE.PCFSoftShadowMap; renderer.outputColorSpace=THREE.SRGBColorSpace; document.querySelector('#app').appendChild(renderer.domElement);
const hemi=new THREE.HemisphereLight(0xffe8c7,0x172033,2.4); scene.add(hemi); const key=new THREE.DirectionalLight(0xffd7a3,4); key.position.set(-5,10,5); key.castShadow=true; scene.add(key); const rim=new THREE.DirectionalLight(0x4f83ff,3.2); rim.position.set(7,5,-7); scene.add(rim);
const floor=new THREE.Mesh(new THREE.PlaneGeometry(40,40),new THREE.MeshToonMaterial({color:0x26201d})); floor.rotation.x=-Math.PI/2; floor.receiveShadow=true; scene.add(floor);
for(let i=0;i<10;i++){const h=2+rand()*5;const w=1.2+rand()*2.4;const box=new THREE.Mesh(new THREE.BoxGeometry(w,h,1.5+rand()*2),new THREE.MeshToonMaterial({color:i%2?0x322925:0x222832}));box.position.set(-13+i*2.8,h/2-0.02,-5-rand()*2);box.castShadow=true;box.receiveShadow=true;scene.add(box)}
for(let i=0;i<12;i++){const lantern=new THREE.Mesh(new THREE.BoxGeometry(.12,.35,.12),new THREE.MeshBasicMaterial({color:i%3===0?0xff455e:0xffc857}));lantern.position.set(-7+i*1.25,2.5+rand()*1.5,-3.7);scene.add(lantern);const light=new THREE.PointLight(lantern.material.color,4,4);light.position.copy(lantern.position);scene.add(light)}
function box(w,h,d,color){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),new THREE.MeshToonMaterial({color}));m.castShadow=true;return m}
function joint(color,r=.16){const m=new THREE.Mesh(new THREE.SphereGeometry(r,10,7),new THREE.MeshToonMaterial({color}));m.castShadow=true;return m}
function chain(parent,upperLen,lowerLen,width,color,skin){const shoulder=new THREE.Group();parent.add(shoulder);const upper=box(width,upperLen,width,color);upper.position.y=-upperLen/2;shoulder.add(upper);const elbow=new THREE.Group();elbow.position.y=-upperLen;shoulder.add(elbow);elbow.add(joint(skin,width*.62));const lower=box(width*.88,lowerLen,width*.88,skin);lower.position.y=-lowerLen/2;elbow.add(lower);const hand=joint(skin,width*.72);hand.position.y=-lowerLen;elbow.add(hand);return {root:shoulder,mid:elbow,end:hand}}
function legChain(parent,upperLen,lowerLen,width,color){const hip=new THREE.Group();parent.add(hip);const upper=box(width,upperLen,width,color);upper.position.y=-upperLen/2;hip.add(upper);const knee=new THREE.Group();knee.position.y=-upperLen;hip.add(knee);knee.add(joint(color,width*.62));const lower=box(width*.9,lowerLen,width*.9,color);lower.position.y=-lowerLen/2;knee.add(lower);const foot=box(width*1.4,.16,width*2.15,0x1a1a1a);foot.position.set(0,-lowerLen,-width*.35);knee.add(foot);return {root:hip,mid:knee,foot}}
function fighter(color,skin){const root=new THREE.Group();const pelvis=new THREE.Group();pelvis.position.y=1.5;root.add(pelvis);const hips=box(.65,.38,.42,color);pelvis.add(hips);const spine=new THREE.Group();spine.position.y=.25;pelvis.add(spine);const torso=box(.78,1.2,.44,color);torso.position.y=.62;spine.add(torso);const neck=new THREE.Group();neck.position.y=1.34;spine.add(neck);const head=joint(skin,.34);head.position.y=.22;neck.add(head);const lArm=chain(spine, .68,.62,.22,color,skin);const rArm=chain(spine, .68,.62,.22,color,skin);lArm.root.position.set(-.5,1.05,0);rArm.root.position.set(.5,1.05,0);const lLeg=legChain(pelvis,.78,.72,.29,color);const rLeg=legChain(pelvis,.78,.72,.29,color);lLeg.root.position.x=-.22;rLeg.root.position.x=.22;root.userData={pelvis,spine,neck,head,lArm,rArm,lLeg,rLeg,velocity:new THREE.Vector3(),guard:0};return root}
const hero=fighter(0xb73732,0xd9a37e);const foe=fighter(0x253b59,0xbd8a6d);scene.add(hero,foe);
let arenaCenter=new THREE.Vector3(0,0,0); hero.position.set(-2.3,0,0); foe.position.set(2.3,0,0);
function ease(x){return x<.5?2*x*x:1-Math.pow(-2*x+2,2)/2} function pulse(x,a,b){if(x<a||x>b)return 0;const n=(x-a)/(b-a);return Math.sin(Math.PI*n)} function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function faceOpponent(a,b){const dx=b.position.x-a.position.x,dz=b.position.z-a.position.z;a.rotation.y=Math.atan2(dx,dz)}
function resetPose(f,t,side=1){const u=f.userData;const breathe=Math.sin(t*2.1)*.025;u.spine.position.y=.25+breathe;u.spine.rotation.z=.025*Math.sin(t*1.7+side);u.neck.rotation.y=.06*Math.sin(t*1.3+side);u.lArm.root.rotation.z=.34;u.rArm.root.rotation.z=-.34;u.lArm.root.rotation.x=-.18;u.rArm.root.rotation.x=-.18;u.lArm.mid.rotation.x=-.85;u.rArm.mid.rotation.x=-.85;u.lLeg.root.rotation.x=.08*Math.sin(t*3.1);u.rLeg.root.rotation.x=-.08*Math.sin(t*3.1);u.lLeg.mid.rotation.x=.08;u.rLeg.mid.rotation.x=.08;u.pelvis.rotation.z=.02*Math.sin(t*2.2)}
function punch(f,amount,right=true){const arm=right?f.userData.rArm:f.userData.lArm;arm.root.rotation.x=-1.55*amount;arm.root.rotation.z=(right?-0.25:0.25)*(1-amount);arm.mid.rotation.x=-.85*(1-amount);f.userData.spine.rotation.y=(right?-.28:.28)*amount}
function kick(f,amount,right=true){const leg=right?f.userData.rLeg:f.userData.lLeg;leg.root.rotation.x=-1.35*amount;leg.root.rotation.z=(right?-.28:.28)*amount;leg.mid.rotation.x=.25-.95*amount;f.userData.spine.rotation.z=(right?.12:-.12)*amount}
function block(f,amount,right=true){const arm=right?f.userData.rArm:f.userData.lArm;arm.root.rotation.x=-1.1*amount;arm.root.rotation.z=(right?-.95:.95)*amount;arm.mid.rotation.x=-1.25*amount}
let mode='technical',cameraMode='director',paused=false;const flash=document.querySelector('#flash'); const clock=new THREE.Clock(); const duration=12;
function choreography(t){resetPose(hero,t,1);resetPose(foe,t,-1);faceOpponent(hero,foe);faceOpponent(foe,hero);const speed=mode==='aggressive'?1.16:mode==='defensive'?.9:1;const tt=(t*speed)%duration;const baseHero=-2.3,baseFoe=2.3;hero.position.x=arenaCenter.x+baseHero+.16*Math.sin(tt*1.25);foe.position.x=arenaCenter.x+baseFoe+.15*Math.sin(tt*1.1+2);hero.position.z=arenaCenter.z+.12*Math.sin(tt*.8);foe.position.z=arenaCenter.z-.12*Math.sin(tt*.9);
let p=pulse(tt,1.0,2.05);hero.position.x+=2.0*ease(p);punch(hero,p,true);block(foe,p,true);foe.position.x+=.25*p;
p=pulse(tt,2.35,3.45);foe.position.x-=1.6*ease(p);kick(foe,p,false);hero.position.x-=.38*p;hero.userData.spine.rotation.z=-.16*p;
p=pulse(tt,3.9,4.75);hero.position.x+=1.0*p;punch(hero,p,false);foe.userData.spine.rotation.z=-.25*p;
p=pulse(tt,5.1,6.2);foe.position.x-=.95*p;punch(foe,p,true);block(hero,p,false);hero.position.z+=.42*p;
p=pulse(tt,6.45,7.45);hero.position.x+=1.0*p;kick(hero,p,true);foe.position.x+=1.05*p;foe.userData.spine.rotation.z=-.4*p;
p=pulse(tt,7.8,8.85);foe.position.x-=1.1*p;punch(foe,p,false);hero.position.x-=.55*p;hero.userData.spine.rotation.z=.18*p;
p=pulse(tt,9.0,10.2);hero.position.x+=2.0*ease(p);punch(hero,p,true);punch(hero,p,false);foe.position.x+=1.0*p;foe.userData.spine.rotation.z=-.62*p;
if(mode==='defensive'){block(hero,pulse(tt,.2,11.5)*.25,true);hero.position.z+=.5*Math.sin(tt*.65)} if(mode==='aggressive'){hero.userData.spine.rotation.x=-.08;foe.userData.spine.rotation.x=-.05}
const hit=Math.max(pulse(tt,1.88,2.02),pulse(tt,4.6,4.74),pulse(tt,7.28,7.42),pulse(tt,9.95,10.12));flash.style.opacity=String(hit*.26);}
function updateCamera(t){const center=new THREE.Vector3().addVectors(hero.position,foe.position).multiplyScalar(.5);if(cameraMode==='director'){camera.position.x=center.x+7.3*Math.cos(t*.11)+Math.sin(t*.7)*.25;camera.position.z=center.z+10.2+Math.sin(t*.18)*-2.4;camera.position.y=4.15+Math.sin(t*.55)*.18}else{camera.position.set(center.x+8.5,3.2,center.z+5.8)}camera.lookAt(center.x,1.65,center.z)}
function animate(){if(!paused){const t=clock.getElapsedTime();choreography(t);updateCamera(t)}renderer.render(scene,camera);requestAnimationFrame(animate)}animate();
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
const raycaster=new THREE.Raycaster(),mouse=new THREE.Vector2();renderer.domElement.addEventListener('pointerdown',e=>{const r=renderer.domElement.getBoundingClientRect();mouse.x=((e.clientX-r.left)/r.width)*2-1;mouse.y=-((e.clientY-r.top)/r.height)*2+1;raycaster.setFromCamera(mouse,camera);const hit=raycaster.intersectObject(floor)[0];if(hit){arenaCenter.x=clamp(hit.point.x,-5,5);arenaCenter.z=clamp(hit.point.z,-2.5,4)}});
document.querySelectorAll('[data-mode]').forEach(btn=>btn.addEventListener('click',()=>{mode=btn.dataset.mode;document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b===btn))}));
const cameraBtn=document.querySelector('#cameraBtn');cameraBtn.addEventListener('click',()=>{cameraMode=cameraMode==='director'?'side':'director';cameraBtn.textContent='CAMERA: '+cameraMode.toUpperCase()});const pauseBtn=document.querySelector('#pauseBtn');pauseBtn.addEventListener('click',()=>{paused=!paused;pauseBtn.textContent=paused?'RESUME':'PAUSE'});
const recordBtn=document.querySelector('#record'); recordBtn.addEventListener('click',()=>{if(!renderer.domElement.captureStream||!window.MediaRecorder){recordBtn.textContent='RECORDING UNSUPPORTED';return}const stream=renderer.domElement.captureStream(30);const chunks=[];let mime='video/webm;codecs=vp9';if(!MediaRecorder.isTypeSupported(mime))mime='video/webm';const rec=new MediaRecorder(stream,{mimeType:mime});rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};rec.onstop=()=>{const blob=new Blob(chunks,{type:mime});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='proofttl-martial-arts-local.webm';a.click();setTimeout(()=>URL.revokeObjectURL(url),1500);recordBtn.disabled=false;recordBtn.textContent='RECORD 12S WEBM'};clock.start();rec.start();recordBtn.disabled=true;recordBtn.textContent='RECORDING…';setTimeout(()=>rec.stop(),12000)});
</script></body></html>`
}

export default function LocalCinematicPreview({ prompt }: { prompt: string }) {
  const [seed, setSeed] = useState(() => Math.floor(Math.random() * 2147483647))
  const srcDoc = useMemo(() => cinematicDocument(prompt, seed), [prompt, seed])
  return (
    <section className="cine-local-movie" data-local-cinematic="true">
      <div className="cine-local-head"><div><span>LOCAL MOVIE ENGINE</span><strong>Humanized interactive martial-arts short</strong></div><button type="button" onClick={() => setSeed(Math.floor(Math.random() * 2147483647))}>NEW TAKE</button></div>
      <iframe title="Local stylized cinematic preview" srcDoc={srcDoc} sandbox="allow-scripts allow-downloads" />
      <small>Articulated elbows and knees, breathing, guard poses, reactions, footwork and opponent-facing motion now run locally. Switch fight behavior and camera mode, pause the action, or click the floor to move the fight before recording.</small>
    </section>
  )
}
