'use client'

import { useMemo, useState } from 'react'
import { parseCinematicPrompt } from '../cinematics/prompt/PromptParser'
import type { CinematicPlan } from '../cinematics/core/Types'

function cinematicDocument(plan: CinematicPlan) {
  const serialized = JSON.stringify(plan).replace(/</g, '\\u003c')
  return `<!doctype html><html><head><meta charset="utf-8"><style>
html,body{margin:0;width:100%;height:100%;overflow:hidden;background:#09090b;font-family:ui-monospace,Menlo,monospace;color:#fff}canvas{display:block;width:100%;height:100%;cursor:crosshair}.hud{position:fixed;inset:0;pointer-events:none}.top{position:absolute;top:10px;left:10px;right:10px;display:flex;justify-content:space-between;gap:8px;font-size:9px;letter-spacing:.1em}.badge{min-height:30px;padding:6px 8px;border:1px solid #ffffff24;background:#08080bcc;backdrop-filter:blur(8px);display:inline-flex;align-items:center;gap:8px}.brand-badge img{display:block;width:92px;height:30px;object-fit:contain}.brand-badge b{font-size:9px;letter-spacing:.08em}.controls{pointer-events:auto;position:absolute;top:54px;left:10px;display:flex;gap:5px;flex-wrap:wrap;max-width:82%}.controls button{border:1px solid #ffffff2f;background:#0d1016e8;color:#fff;padding:6px 8px;font:700 9px ui-monospace,Menlo,monospace;letter-spacing:.05em;cursor:pointer}.controls button.active{border-color:#f2c94c;color:#f2c94c}.bottom{position:absolute;left:10px;right:10px;bottom:10px;display:grid;grid-template-columns:minmax(0,1fr) auto;gap:8px;align-items:end}.timeline{pointer-events:auto;background:#08080bdc;border:1px solid #ffffff20;padding:8px;display:grid;gap:6px}.timeline-row{display:flex;align-items:center;gap:8px}.timeline input{width:100%}.timeline small{color:#aaa;white-space:nowrap}.prompt{font:9px/1.35 ui-monospace,Menlo,monospace;color:#cfd3da;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.record{pointer-events:auto;border:1px solid #ffffff35;background:#111318e8;color:#fff;padding:9px 10px;font:700 9px ui-monospace,Menlo,monospace;letter-spacing:.06em;cursor:pointer}.record:disabled{opacity:.5}.flash{position:absolute;inset:0;background:white;opacity:0;mix-blend-mode:screen}.impact{position:absolute;left:50%;top:42%;transform:translate(-50%,-50%);font:bold 28px system-ui;opacity:0;text-shadow:0 2px 15px #000}.hint{position:absolute;right:10px;top:88px;padding:6px 8px;background:#08080baa;border:1px solid #ffffff1c;color:#aaa;font-size:8px}
</style></head><body><div id="app"></div><div class="hud"><div class="top"><span class="badge brand-badge"><img src="/proofttl-logo.png" alt="ProofTTL"><b>CINEMATICS V2</b></span><span class="badge" id="status">LOCAL ENGINE · READY</span></div><div class="controls"><button data-style="technical">TECHNICAL</button><button data-style="aggressive">AGGRESSIVE</button><button data-style="defensive">DEFENSIVE</button><button data-style="cinematic">CINEMATIC</button><button id="cameraBtn">CAMERA: WIDE</button><button id="pauseBtn">PAUSE</button><button id="takeBtn">NEW MICRO-TAKE</button></div><div class="hint">CLICK FLOOR TO REPOSITION FIGHT · TIMELINE IS SCRUBBABLE</div><div class="flash" id="flash"></div><div class="impact" id="impact">IMPACT</div><div class="bottom"><div class="timeline"><div class="prompt" id="prompt"></div><div class="timeline-row"><small id="timeLabel">0.0s</small><input id="scrub" type="range" min="0" max="1000" value="0"><small id="durationLabel"></small></div></div><button class="record" id="record">RECORD WEBM</button></div></div><script type="module">
import * as THREE from 'https://esm.sh/three@0.179.1';
const plan=${serialized}; document.querySelector('#prompt').textContent=plan.prompt; document.querySelector('#durationLabel').textContent=plan.duration.toFixed(1)+'s';
let rngState=plan.seed||1; const rand=()=>((rngState=Math.imul(1664525,rngState)+1013904223|0)>>>0)/4294967296; const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)); const smooth=x=>x*x*(3-2*x); const pulse=(t,a,b)=>t<a||t>b?0:Math.sin(Math.PI*(t-a)/(b-a));
const scene=new THREE.Scene(); const palettes={restaurant_kitchen:[0x12151a,0x2e363f,0x8aa0aa],hallway:[0x121016,0x2b2330,0x9c7f6a],warehouse:[0x111416,0x303437,0x8b6b43],nightclub:[0x090914,0x241b38,0x6c4ad2],rooftop:[0x10151c,0x253244,0x6a829b],alley:[0x0d1114,0x20282e,0x60747f],apartment:[0x17120f,0x3c2d26,0x9a745b],dojo:[0x17110d,0x3a2b20,0xb48d62],courtyard:[0x111216,0x292b33,0x77808f]}; const pal=palettes[plan.environment]||palettes.courtyard; scene.background=new THREE.Color(pal[0]); scene.fog=new THREE.Fog(pal[0],12,36);
const camera=new THREE.PerspectiveCamera(44,innerWidth/innerHeight,.1,100); camera.position.set(6.2,3.8,8.4); const renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true}); renderer.setPixelRatio(Math.min(devicePixelRatio,1.6)); renderer.setSize(innerWidth,innerHeight); renderer.shadowMap.enabled=true; renderer.shadowMap.type=THREE.PCFSoftShadowMap; renderer.outputColorSpace=THREE.SRGBColorSpace; document.querySelector('#app').appendChild(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xffe8c7,0x111827,1.8)); const key=new THREE.DirectionalLight(0xffd5a3,3.1); key.position.set(-5,10,5); key.castShadow=true; key.shadow.mapSize.set(1024,1024); scene.add(key); const rim=new THREE.DirectionalLight(0x4f83ff,2.2); rim.position.set(7,4,-7); scene.add(rim);
const floor=new THREE.Mesh(new THREE.PlaneGeometry(40,40),new THREE.MeshToonMaterial({color:pal[1]})); floor.rotation.x=-Math.PI/2; floor.receiveShadow=true; scene.add(floor);
function toon(color){return new THREE.MeshToonMaterial({color})} function meshBox(w,h,d,color){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),toon(color));m.castShadow=true;m.receiveShadow=true;return m} function ball(r,color){const m=new THREE.Mesh(new THREE.SphereGeometry(r,16,12),toon(color));m.castShadow=true;return m} function capsule(r,len,color){const m=new THREE.Mesh(new THREE.CapsuleGeometry(r,len,6,10),toon(color));m.castShadow=true;return m} function torso(color){const m=new THREE.Mesh(new THREE.CylinderGeometry(.34,.43,.78,10),toon(color));m.castShadow=true;return m}
function addProp(type,x,z,sx=1,sz=1){const color=type==='metal'?0x5b6570:type==='wood'?0x5a3828:0x30343a;const h=type==='table'?.82:type==='counter'?1:type==='wall'?3:.5;const p=meshBox(type==='wall'?sx:1.6*sx,h,type==='wall'?sz:.85*sz,color);p.position.set(x,h/2,z);scene.add(p);return p}
function environment(){if(plan.environment==='restaurant_kitchen'){for(let i=-2;i<=2;i++)addProp('metal',i*2.6,-3.8,1.1,.8);addProp('table',0,.6,1.4,1);addProp('counter',-5,1.5,1,2.4);addProp('counter',5,1.5,1,2.4)}else if(plan.environment==='dojo'){addProp('wall',0,-6,12,.3);for(let i=-2;i<=2;i++)addProp('wood',i*2.5,-4.8,.3,.3)}else if(plan.environment==='warehouse'){for(let i=0;i<6;i++)addProp('metal',-7+(i%3)*7,-5+Math.floor(i/3)*9,1.4,1.2)}else{for(let i=0;i<8;i++){const h=1.5+rand()*4;const b=meshBox(1.5+rand()*2,h,1.5+rand()*2,i%2?pal[1]:0x242832);b.position.set(-10+i*3,h/2,-6-rand()*2);scene.add(b)}}} environment();
function makeArm(parent,side,color,skin){const shoulder=new THREE.Group();shoulder.position.set(.46*side,.92,0);parent.add(shoulder);shoulder.add(ball(.15,color));const upper=capsule(.105,.38,color);upper.position.y=-.31;shoulder.add(upper);const elbow=new THREE.Group();elbow.position.y=-.62;shoulder.add(elbow);elbow.add(ball(.115,skin));const fore=capsule(.09,.35,skin);fore.position.y=-.29;elbow.add(fore);const wrist=new THREE.Group();wrist.position.y=-.57;elbow.add(wrist);const hand=capsule(.09,.10,skin);hand.rotation.z=Math.PI/2;wrist.add(hand);return{shoulder,elbow,wrist,hand}}
function makeLeg(parent,side,color){const hip=new THREE.Group();hip.position.set(.21*side,0,0);parent.add(hip);hip.add(ball(.16,color));const thigh=capsule(.145,.48,color);thigh.position.y=-.39;hip.add(thigh);const knee=new THREE.Group();knee.position.y=-.77;hip.add(knee);knee.add(ball(.14,color));const calf=capsule(.125,.43,color);calf.position.y=-.35;knee.add(calf);const ankle=new THREE.Group();ankle.position.y=-.70;knee.add(ankle);const foot=meshBox(.3,.14,.5,0x171717);foot.position.z=-.12;ankle.add(foot);return{hip,knee,ankle,foot}}
function fighter(color,skin,scale=.98){const root=new THREE.Group();root.scale.setScalar(scale);const pelvis=new THREE.Group();pelvis.position.y=1.53;root.add(pelvis);const hips=new THREE.Mesh(new THREE.CylinderGeometry(.31,.34,.32,10),toon(color));pelvis.add(hips);const spine1=new THREE.Group();spine1.position.y=.24;pelvis.add(spine1);const spine2=new THREE.Group();spine2.position.y=.34;spine1.add(spine2);const chest=torso(color);chest.position.y=.38;spine2.add(chest);const neck=new THREE.Group();neck.position.y=.82;spine2.add(neck);const neckMesh=capsule(.09,.08,skin);neckMesh.position.y=.04;neck.add(neckMesh);const head=ball(.31,skin);head.scale.set(1,.95,.9);head.position.y=.31;neck.add(head);const nose=new THREE.Mesh(new THREE.ConeGeometry(.055,.13,5),toon(skin));nose.rotation.x=Math.PI/2;nose.position.set(0,.30,-.29);neck.add(nose);const la=makeArm(spine2,-1,color,skin),ra=makeArm(spine2,1,color,skin),ll=makeLeg(pelvis,-1,color),rl=makeLeg(pelvis,1,color);root.userData={pelvis,spine1,spine2,neck,head,la,ra,ll,rl,phase:rand()*6.28,slot:0};return root}
const hero=fighter(0xb73732,0xd9a37e,1.03); scene.add(hero); const enemies=[]; const enemyColors=[0x263d5d,0x384052,0x443650,0x2e4b45,0x4d3b2d,0x35344f,0x4c3440,0x30414a]; for(let i=0;i<plan.attackers;i++){const e=fighter(enemyColors[i%enemyColors.length],i%2?0xb98264:0xc99672,.94+rand()*.08);e.userData.slot=i;scene.add(e);enemies.push(e)}
let arenaCenter=new THREE.Vector3(); function resetPositions(){hero.position.set(arenaCenter.x-1.25,0,arenaCenter.z);for(let i=0;i<enemies.length;i++){const angle=(i/enemies.length)*Math.PI*2;const r=2.8+(i%2)*.55;enemies[i].position.set(arenaCenter.x+Math.cos(angle)*r,0,arenaCenter.z+Math.sin(angle)*r)}} resetPositions(); camera.lookAt(0,1.55,0);
function face(a,b){const d=b.position.clone().sub(a.position);a.rotation.y=Math.atan2(-d.x,-d.z)}
function basePose(f,t,energy=0){const u=f.userData,breath=Math.sin(t*(1.7+energy*.8)+u.phase)*(.018+energy*.01),shift=Math.sin(t*.72+u.phase)*.025;u.pelvis.position.y=1.53+breath;u.pelvis.position.x=shift;u.pelvis.rotation.set(0,0,-shift*.3);u.spine1.rotation.set(.025+energy*.035,0,0);u.spine2.rotation.set(0,0,-shift*.45);u.neck.rotation.set(0,Math.sin(t*.53+u.phase)*.045,0);u.la.shoulder.rotation.set(-.15,0,.42);u.ra.shoulder.rotation.set(-.15,0,-.42);u.la.elbow.rotation.x=-1.05;u.ra.elbow.rotation.x=-1.05;u.la.wrist.rotation.set(0,0,.08);u.ra.wrist.rotation.set(0,0,-.08);u.ll.hip.rotation.set(.02,0,.02);u.rl.hip.rotation.set(-.02,0,-.02);u.ll.knee.rotation.x=.11;u.rl.knee.rotation.x=.11;f.rotation.z*=.82;f.rotation.x*=.82}
function strike(f,p,right=true,kind='punch'){const u=f.userData;if(kind==='kick'||kind==='spin'){const leg=right?u.rl:u.ll;leg.hip.rotation.x=-1.2*p;leg.hip.rotation.z=(right?-.42:.42)*p;leg.knee.rotation.x=.1-.72*p;u.spine2.rotation.z=(right?.18:-.18)*p}else{const a=right?u.ra:u.la;a.shoulder.rotation.x=-1.48*p;a.shoulder.rotation.z=(right?-.18:.18)*(1-p);a.elbow.rotation.x=-1.05*(1-p);u.spine2.rotation.y=(right?-.34:.34)*p;u.pelvis.rotation.y=(right?-.12:.12)*p}}
function guard(f,p,right=true){const a=right?f.userData.ra:f.userData.la;a.shoulder.rotation.x=-.95*p;a.shoulder.rotation.z=(right?-.9:.9)*p;a.elbow.rotation.x=-1.35*p;f.userData.spine2.rotation.y=(right?.12:-.12)*p}
function dodge(f,p,side=1){f.position.x+=side*.65*p;f.userData.pelvis.rotation.z=-side*.13*p;f.userData.spine2.rotation.z=side*.2*p;f.userData.neck.rotation.z=side*.1*p}
function stagger(f,p,dir=1){f.position.x+=dir*.35*p;f.rotation.z=-dir*.2*p;f.userData.spine2.rotation.x=-.18*p;f.userData.neck.rotation.x=.18*p}
function actionProgress(local,duration){return pulse(local,0,duration)} function actorById(id){if(id==='hero')return hero;const n=Number(String(id).split('-')[1]||1)-1;return enemies[clamp(n,0,enemies.length-1)]}
let style=plan.style,cameraMode=plan.cameraStyle==='overhead'?'overhead':plan.cameraStyle==='side'?'side':plan.cameraStyle==='handheld'?'handheld':'wide',paused=false,manualTime=0,scrubbing=false,microSeed=0; const flash=document.querySelector('#flash'),impact=document.querySelector('#impact'),scrub=document.querySelector('#scrub'),timeLabel=document.querySelector('#timeLabel'),status=document.querySelector('#status'); const cameraBtn=document.querySelector('#cameraBtn'); cameraBtn.textContent='CAMERA: '+cameraMode.toUpperCase();
function resetFrame(t){const energy=style==='aggressive'?.75:style==='defensive'?.25:.45;basePose(hero,t,energy);for(const e of enemies)basePose(e,t,.38);for(const e of enemies)face(e,hero);if(enemies[0])face(hero,enemies[0]);impact.style.opacity='0';flash.style.opacity='0'}
function crowdMotion(t){for(let i=0;i<enemies.length;i++){const e=enemies[i],angle=(i/enemies.length)*Math.PI*2+.14*Math.sin(t*.35+i),active=plan.actions.some(a=>a.actorId===('enemy-'+(i+1))&&t>=a.start-.55&&t<=a.start+a.duration+.5);const targetR=active?1.65:2.65+(i%2)*.45;const tx=arenaCenter.x+Math.cos(angle)*targetR,tz=arenaCenter.z+Math.sin(angle)*targetR;e.position.x+=(tx-e.position.x)*.055;e.position.z+=(tz-e.position.z)*.055;if(!active){e.userData.spine2.rotation.y+=Math.sin(t*.7+i)*.035;e.userData.pelvis.position.y+=Math.sin(t*1.5+i)*.01}}}
function evalActions(t){let maxImpact=0;for(const a of plan.actions){const local=t-a.start;if(local<-.45||local>a.duration+.55)continue;const actor=actorById(a.actorId),target=a.targetId?actorById(a.targetId):null;if(!actor)continue;if(target)face(actor,target);const p=actionProgress(local,a.duration);if(a.action==='approach'&&target){const d=target.position.clone().sub(actor.position);d.y=0;if(d.length()>1.45){d.normalize().multiplyScalar(.035*p);actor.position.add(d)}}else if(a.action==='jab'||a.action==='cross'||a.action==='hook'){strike(actor,p,a.action!=='jab','punch')}else if(a.action==='kick'){strike(actor,p,true,'kick')}else if(a.action==='spinning_kick'){strike(actor,p,true,'spin');actor.rotation.y+=smooth(clamp(local/a.duration,0,1))*Math.PI*2}else if(a.action==='block'||a.action==='parry'){guard(actor,p,a.action==='block')}else if(a.action==='dodge'){dodge(actor,p,actor===hero?-1:1)}else if(a.action==='throw'&&target){guard(actor,p,true);const q=smooth(clamp(local/a.duration,0,1));target.position.lerp(new THREE.Vector3(arenaCenter.x+1.2,0,arenaCenter.z-.2),.055*q);target.rotation.z=-.75*p}else if(a.action==='stagger'){stagger(actor,p,actor===hero?-1:1)}if(a.outcome==='hit'||a.outcome==='throw_success'){const hit=pulse(local,a.duration*.47,a.duration*.58);if(target)stagger(target,hit,actor.position.x<target.position.x?1:-1);maxImpact=Math.max(maxImpact,hit*(a.cameraWeight||.6))}if(a.outcome==='blocked'){const hit=pulse(local,a.duration*.44,a.duration*.54);if(target)guard(target,hit,true);maxImpact=Math.max(maxImpact,hit*.45)}}if(maxImpact>.05){flash.style.opacity=String(maxImpact*.24);impact.style.opacity=String(maxImpact*.75);impact.style.transform='translate(-50%,-50%) scale('+(1+maxImpact*.18)+')'}return maxImpact}
function footPlant(f){for(const leg of [f.userData.ll,f.userData.rl]){leg.ankle.rotation.x*=.6;leg.ankle.position.y=0}}
function cameraUpdate(t,hit){const all=[hero,...enemies],center=new THREE.Vector3();for(const a of all)center.add(a.position);center.multiplyScalar(1/all.length);const high=plan.actions.filter(a=>t>=a.start&&t<=a.start+a.duration).sort((a,b)=>(b.cameraWeight||0)-(a.cameraWeight||0))[0],target=high?actorById(high.actorId):hero;const focus=(cameraMode==='wide'||cameraMode==='overhead'||cameraMode==='side')?center.clone():(target?target.position.clone().lerp(high?.targetId?actorById(high.targetId)?.position||target.position:target.position,.45):center.clone());focus.y=1.55;const desired=new THREE.Vector3();if(cameraMode==='side')desired.set(center.x+6.8,2.9,center.z+4.8);else if(cameraMode==='wide')desired.set(center.x+6.2,3.8,center.z+8.4);else if(cameraMode==='overhead')desired.set(center.x+1.6,8.5,center.z+1.6);else desired.set(focus.x+4.1,2.8,focus.z+5.3);const shake=hit*(cameraMode==='handheld'?.16:.035);desired.x+=Math.sin(t*71)*shake;desired.y+=Math.sin(t*59)*shake*.6;if(cameraMode==='handheld')camera.position.lerp(desired,.16);else camera.position.copy(desired);camera.fov=44;camera.updateProjectionMatrix();camera.lookAt(focus)}
function renderAt(t){resetFrame(t);crowdMotion(t);const hit=evalActions(t);for(const a of [hero,...enemies])footPlant(a);cameraUpdate(t,hit);renderer.render(scene,camera);timeLabel.textContent=t.toFixed(1)+'s';if(!scrubbing)scrub.value=String(Math.round((t/plan.duration)*1000))}
const clock=new THREE.Clock();let last=0;function animate(){requestAnimationFrame(animate);if(!paused&&!scrubbing){const now=clock.getElapsedTime(),dt=clamp(now-last,0,.05);last=now;manualTime=(manualTime+dt)%plan.duration}renderAt(manualTime)}animate();
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});const raycaster=new THREE.Raycaster(),mouse=new THREE.Vector2();renderer.domElement.addEventListener('pointerdown',e=>{const r=renderer.domElement.getBoundingClientRect();mouse.x=((e.clientX-r.left)/r.width)*2-1;mouse.y=-((e.clientY-r.top)/r.height)*2+1;raycaster.setFromCamera(mouse,camera);const hit=raycaster.intersectObject(floor)[0];if(hit){arenaCenter.set(clamp(hit.point.x,-5,5),0,clamp(hit.point.z,-3,4));resetPositions()}});
document.querySelectorAll('[data-style]').forEach(btn=>{if(btn.dataset.style===style)btn.classList.add('active');btn.addEventListener('click',()=>{style=btn.dataset.style;document.querySelectorAll('[data-style]').forEach(b=>b.classList.toggle('active',b===btn));status.textContent='STYLE · '+style.toUpperCase()})});cameraBtn.addEventListener('click',()=>{const modes=['wide','side','overhead','handheld'];cameraMode=modes[(modes.indexOf(cameraMode)+1)%modes.length];cameraBtn.textContent='CAMERA: '+cameraMode.toUpperCase();status.textContent='CAMERA · '+cameraMode.toUpperCase()});const pauseBtn=document.querySelector('#pauseBtn');pauseBtn.addEventListener('click',()=>{paused=!paused;pauseBtn.textContent=paused?'RESUME':'PAUSE'});document.querySelector('#takeBtn').addEventListener('click',()=>{microSeed++;rngState=(plan.seed+microSeed*7919)|0;status.textContent='MICRO-TAKE '+(microSeed+1)+' · READY'});scrub.addEventListener('pointerdown',()=>scrubbing=true);scrub.addEventListener('input',()=>{manualTime=(Number(scrub.value)/1000)*plan.duration;renderAt(manualTime)});scrub.addEventListener('change',()=>{scrubbing=false;last=clock.getElapsedTime()});
const recordBtn=document.querySelector('#record');recordBtn.addEventListener('click',()=>{if(!renderer.domElement.captureStream||!window.MediaRecorder){recordBtn.textContent='UNSUPPORTED';return}const stream=renderer.domElement.captureStream(30),chunks=[];let mime='video/webm;codecs=vp9';if(!MediaRecorder.isTypeSupported(mime))mime='video/webm';const rec=new MediaRecorder(stream,{mimeType:mime});rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};rec.onstop=()=>{const blob=new Blob(chunks,{type:mime}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='proofttl-cinematic-v2.webm';a.click();setTimeout(()=>URL.revokeObjectURL(url),1500);recordBtn.disabled=false;recordBtn.textContent='RECORD WEBM';status.textContent='EXPORT · COMPLETE'};manualTime=0;last=clock.getElapsedTime();paused=false;rec.start();recordBtn.disabled=true;recordBtn.textContent='RECORDING…';status.textContent='EXPORT · RECORDING';setTimeout(()=>rec.stop(),plan.duration*1000)});
</script></body></html>`
}

export default function LocalCinematicPreview({ prompt }: { prompt: string }) {
  const [seed, setSeed] = useState(() => Math.floor(Math.random() * 2147483647))
  const plan = useMemo(() => parseCinematicPrompt(prompt, seed), [prompt, seed])
  const srcDoc = useMemo(() => cinematicDocument(plan), [plan])
  return (
    <section className="cine-local-movie" data-local-cinematic="true" data-cinematic-schema="proofttl-cinematic-v2">
      <div className="cine-local-head">
        <div><span>LOCAL MOVIE ENGINE · V2</span><strong>{plan.attackers > 1 ? `1 vs ${plan.attackers} · ` : ''}{plan.environment.replaceAll('_', ' ')} · {plan.style}</strong></div>
        <button type="button" onClick={() => setSeed(Math.floor(Math.random() * 2147483647))}>REGENERATE TAKE</button>
      </div>
      <iframe title="ProofTTL Cinematics v2 local runtime" srcDoc={srcDoc} sandbox="allow-scripts allow-downloads" />
      <small>Prompt-planned locally: {plan.actors.length} actors · {plan.actions.length} choreographed events · {plan.duration.toFixed(1)}s. Scrub, reposition, change fight/camera style, and export WebM without a paid provider.</small>
    </section>
  )
}
