'use client';

import { useEffect, useState } from 'react';
import styles from './cognition.module.css';

type Any=Record<string,any>;
const API='/api/edon/status?conversationId=default';

export default function CognitionPage(){
  const [status,setStatus]=useState<Any|null>(null);const [error,setError]=useState('');
  useEffect(()=>{let dead=false;const load=async()=>{try{const r=await fetch(API,{cache:'no-store'}),b=await r.json();if(!r.ok)throw new Error(b?.error||`HTTP ${r.status}`);if(!dead){setStatus(b);setError('')}}catch(e){if(!dead)setError(e instanceof Error?e.message:String(e))}};void load();const id=setInterval(load,2200);return()=>{dead=true;clearInterval(id)}},[]);
  const identity=status?.identity||{};const c=identity?.cognition||status?.cognition||{};const cortical=c?.cortical||{};const predictive=c?.predictive||{};const workspace=c?.workspace||{};const mod=c?.modulators||{};const temporal=c?.temporal||{};const worldModel=c?.worldModel||{};const memories=Array.isArray(status?.retrievedMemories)?status.retrievedMemories:[];const threads=Array.isArray(status?.openThreads)?status.openThreads:[];const drives=identity?.drives||{};
  const layers=[
    {n:'00',title:'Temporal dynamics',tag:'SIGNAL STATE',body:'Decaying traces, salience pulses and refractory windows provide short-timescale state without pretending to simulate biological ion channels.',stats:[['TRACES',temporal?.traces?.length??0],['PULSES',temporal?.pulses?.length??0],['UPDATED',ago(temporal?.updatedAt)]]},
    {n:'01',title:'Cortical abstraction',tag:'FEATURE LAYER',body:String(cortical?.sensory||'No active measured scene.').slice(0,260),chips:[...(cortical?.features||[]),...(cortical?.abstract||[])].slice(0,10)},
    {n:'02',title:'Predictive hierarchy',tag:'PREDICTION / ERROR',body:String(predictive?.predictedScene||'No current scene prediction.').slice(0,260),stats:[['ERROR',fmt(predictive?.predictionError)],['SURPRISE',fmt(predictive?.surprise)],['COMPARED',ago(predictive?.lastComparedAt)]]},
    {n:'03',title:'Global workspace',tag:'ATTENTION BROADCAST',body:String(workspace?.winner?.content||'No winner is currently occupying the limited workspace.').slice(0,340),chips:(workspace?.broadcast||[]).map((x:any)=>`${x.source}: ${x.content}`).slice(0,6),stats:[['CAPACITY',workspace?.capacity??4],['ACTIVE',workspace?.items?.length??0],['CYCLES',c?.cycles??0]]},
    {n:'04',title:'Long-term continuity',tag:'FAST / SLOW MEMORY',body:'Persistent associative memory, open threads, reflections and consolidation feed context back into later cognition.',stats:[['RETRIEVED',memories.length],['OPEN THREADS',threads.length],['MEMORY STATE',status?.safety?.memoryFrozen?'FROZEN':'PLASTIC']]},
    {n:'05',title:'Valuation + modulation',tag:'COMPUTATIONAL GAINS',body:'These are control variables that gate salience, uncertainty, stability and action. They are not claims about literal neurotransmitters.',meters:[['Novelty',mod?.noveltyGain],['Uncertainty',mod?.uncertaintyGain],['Stability',mod?.stabilityGain],['Action',mod?.actionGain]],stats:[['RPE',signed(mod?.rewardPredictionError)],['BACKGROUND',status?.permissions?.backgroundModel?'ON':'OFF']]},
    {n:'06',title:'Embodiment + closed loop',tag:'WORLD MODEL',body:String(worldModel?.embodiedGoal||status?.world?.autonomy?.goal||'No embodied goal reported.').slice(0,300),chips:Object.entries(drives).sort((a:any,b:any)=>Number(b[1])-Number(a[1])).slice(0,6).map(([k,v])=>`${k} ${Math.round(Number(v)*100)}%`),stats:[['WORLD OBJECTS',worldModel?.objectCount??status?.world?.objects?.length??0],['CAMERA ENTITIES',worldModel?.cameraEntityCount??0],['SCENE CONF',fmt(worldModel?.confidence)]]}
  ];
  return <main className={styles.shell}><header><p>UNIFIED ENTITY · COGNITIVE STACK</p><h1>Layered cognition, measured.</h1><span>Functional computational layers inspired by neuroscience. No claim of literal biological neurons or consciousness.</span></header>{error&&<div className={styles.error}>{error}</div>}<section className={styles.grid}>{layers.map(layer=><article key={layer.n} className={styles.card}><div className={styles.head}><b>{layer.n}</b><div><small>{layer.tag}</small><h2>{layer.title}</h2></div></div><p className={styles.body}>{layer.body}</p>{layer.chips?.length?<div className={styles.chips}>{layer.chips.map((x:any,i:number)=><span key={i}>{String(x)}</span>)}</div>:null}{layer.meters?.length?<div className={styles.meters}>{layer.meters.map(([name,value]:any)=><div key={name}><label><span>{name}</span><b>{fmt(value)}</b></label><i><em style={{width:`${Math.round(Math.max(0,Math.min(1,Number(value)||0))*100)}%`}}/></i></div>)}</div>:null}{layer.stats?.length?<div className={styles.stats}>{layer.stats.map(([k,v]:any)=><div key={k}><span>{k}</span><b>{String(v)}</b></div>)}</div>:null}</article>)}</section><footer><span>Last runtime update {ago(c?.updatedAt)}</span><a href="/">ENTITY</a><a href="/evolution">EVOLUTION</a><a href="/systems">SYSTEMS</a></footer></main>
}
function fmt(v:any){return Number.isFinite(Number(v))?Number(v).toFixed(2):'—'}function signed(v:any){const n=Number(v);return Number.isFinite(n)?`${n>=0?'+':''}${n.toFixed(2)}`:'—'}function ago(v:any){const t=Date.parse(String(v||''));if(!Number.isFinite(t))return 'never';const s=Math.max(0,Math.round((Date.now()-t)/1000));return s<3?'now':s<60?`${s}s ago`:s<3600?`${Math.round(s/60)}m ago`:`${Math.round(s/3600)}h ago`}
